version: '3'
services:
  mysql-8.0.33-debian:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        VARIANT: 8.0.33
      target: debian
    image: seanly/dbset:mysql-8.0.33-debian
    restart: unless-stopped
    tty: true
    entrypoint: /bin/bash

  mysql-8.0.33:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        VARIANT: 8.0.33
      target: oracle
    image: seanly/dbset:mysql-8.0.33
    restart: unless-stopped
    tty: true
    entrypoint: /bin/bash
