version: '3'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:9.0.6-ce.0'
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '2222:22'
    volumes:
      - './config:/etc/gitlab'
      - './data:/var/opt/gitlab'
      - '/data/backup:/var/opt/gitlab/backups'
    shm_size: '256m'