version: '3'
services:
  elasticsearch:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        - VERSION=7.17.18
      target: elasticsearch
    image: seanly/dbset:elasticsearch-7.17.18
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      node.name: es01
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      discovery.type: single-node
      bootstrap.memory_lock: true
      xpack.security.enabled: true
      ELASTIC_PASSWORD: "admin123"
    ports:
    - 9200:9200
    - 9300:9300
    volumes:
      - es-data:/data/db

  kibana:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        - VERSION=7.17.18
      target: kibana
    image: seanly/dbset:kibana-7.17.18
    container_name: kibana
    restart: always
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: "admin123"

  logstash:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        - VERSION=7.17.18
      target: kibana
    image: seanly/dbset:logstash-7.17.18
    container_name: logstash
    restart: always

networks:
  default:
    name: opsbox-network
    external: true

volumes:
  es-data: