version: '3'
services:
  mysql-5.7.35:
    build:
      context: ./5.7
      args:
        VARIANT: 5.7.35
    image: seanly/dbextra:mysql-5.7.35
    restart: unless-stopped
    tty: true
    entrypoint: /bin/bash
  mysql-5.7.42-debian:
    build:
      context: ./5.7
      args:
        VARIANT: 5.7.42-debian
    image: seanly/dbextra:mysql-5.7.42
    restart: unless-stopped
    tty: true
    entrypoint: /bin/bash