version: '3'
services:
  redis:
    image: seanly/dbset:redis-6.2.14
    restart: unless-stopped
    volumes:
      - redis-data:/data    
    environment:
      - TZ=Asia/Shanghai
    command: redis-server --requirepass redis@root --appendonly yes --protected-mode no --tcp-backlog "20480"


networks:
  default:
    name: opsbox-network
    external: true

volumes:
  redis-data: